#!/bin/bash

source ./shell/core-bash.sh

TMP=/tmp/elgatodep-$RANDOM;
DATA_DIR=/data #where mysql data is stored

mkdir -p $TMP; cd $TMP;

# node is required for elgatokb
function install_node ()
{
	git clone https://github.com/joyent/node.git
	cd node; ./configure; make; make install;
	cd ../;
}

# npm module for node.js
function install_npm ()
{
	curl http://npmjs.org/install.sh > install-npm.sh;
	chmod 755 install-npm.sh; ./install-npm.sh;
	
	# TODO - npm install
}


function on_confirm_n () 
{
	npm install n -g;
}

#version control for node.js
function install_n ()
{
	confirm "Would you like to install N? (manages node.js versions)" "on_confirm_n";
}



install-all node npm n

# done installing, cleanup
rm -rf $TMP;